"""added patient tables

Revision ID: 558b373705d6
Revises: b1f0331537ff
Create Date: 2024-03-26 18:00:20.524733

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '558b373705d6'
down_revision = 'b1f0331537ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
