"""added patient tables

Revision ID: 98d3e7c5eb72
Revises: 4b7db8cae0ad
Create Date: 2024-03-22 12:02:45.821988

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '98d3e7c5eb72'
down_revision = '4b7db8cae0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
