"""added patient tables

Revision ID: b07680fed333
Revises: e2412789c190
Create Date: 2024-03-22 11:49:44.196096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b07680fed333'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbc',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('hb', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hb_untis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('hba1c',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('labsupportedtests',
    sa.Column('cbc', sa.Boolean(), nullable=False),
    sa.Column('hba1c', sa.Boolean(), nullable=False),
    sa.Column('thyroid', sa.Boolean(), nullable=False),
    sa.Column('labid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('labid')
    )
    op.create_table('patient',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('unassigned', 'trail', 'demo', 'guest', 'patient', 'lab_technitian', 'local_admin', 'branch_admin', 'group_admin', 'super_admin', 'owner', 'deployer', 'developer', 'root', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=True)
    op.create_table('patientoptedtests',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('patienttestrequestid',
    sa.Column('reqid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reqid')
    )
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('unassigned', 'trail', 'demo', 'guest', 'patient', 'lab_technitian', 'local_admin', 'branch_admin', 'group_admin', 'super_admin', 'owner', 'deployer', 'developer', 'root', name='role'), nullable=False))
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    op.drop_column('user', 'uuid')
    op.drop_column('user', 'age')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('patienttestrequestid')
    op.drop_table('patientoptedtests')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_table('labsupportedtests')
    op.drop_table('hba1c')
    op.drop_table('cbc')
    # ### end Alembic commands ###
