"""added patient tables

Revision ID: b1f0331537ff
Revises: 98d3e7c5eb72
Create Date: 2024-03-26 17:57:44.733089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1f0331537ff'
down_revision = '98d3e7c5eb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
