"""added patient tables

Revision ID: c1bacfd67188
Revises: 3b30c89b283b
Create Date: 2024-03-22 11:59:05.153406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c1bacfd67188'
down_revision = '3b30c89b283b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.drop_column('patient', 'is_super_user')
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_super_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_superuser')
    op.add_column('patient', sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('patient', 'is_superuser')
    # ### end Alembic commands ###
